// JsFromRoutes CacheKey b3099a5f35e2fe93c633cccbf5795f5e
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  home: definePathHelper('get', '/'),
}
